<table class="table table-bordered responsive-table">
    <tbody>
        <tr>
            <th>
                @lang('strings.title')
            </th>
        </tr>
        <tr>
            <td>
                {{$freePages->title}}
            </td>
        </tr>
        <tr>
            <th>
                @lang('strings.free_page_code')
            </th>
        </tr>
        <tr>
            <td>
                {{$freePages->code}}
            </td>
        </tr>
        <tr>
            <th>
                @lang('strings.body')
            </th>
        </tr>
        <tr>
            <td>
                {!! $freePages->body ?? old('body') !!}
            </td>
        </tr>
    </tbody>
</table>